### PR TITLE
External version banner initial style

### PR DESCRIPTION
**Pull request by humitos**
I'm opening this PR here to receive the _initial_ feedback because I'm sure this is not probably the path we want to follow. My CSS skills are hardcoded in the 90's still 😄 

Screenshot_2023-03-22_23-33-13

See it in action at: https://readthedocs-client--18.org.readthedocs.build/en/18/pelican/

### CODE REVIEW

**Comment by humitos** [comment]
@agjohnson I'm marking this PR for review to receive some initial feedback.

**Comment by agjohnson** [comment]
I might have some suggestions for playing around with some of the styles and content here. Is it possible to bring up the warning banner using the dev server QA tests?

**Comment by humitos** [comment]
Or, even, you can play directly from the build from the PR in Read the Docs 🚀 at https://readthedocs-client--18.org.readthedocs.build/en/18/pelican/

**Comment by humitos** [comment]
This is what I currently have. I'm staying more conservative with the colors because I don't have those skills 😄 . I'm trying to match the simplicity that we are following in the search UI regarding the amount of colors.

It also follows, more or less, some of the same colors from EthicalAds.

Screenshot_2023-03-30_02-00-10

**Comment by humitos** [comment]
Updates

Peek 2023-04-04 20-04


Peek 2023-04-04 20-00

**Comment by agjohnson** [comment]
The "warning" bar at the top is nice, but perhaps this could use something other than "warning" as copy? I'd have to think of replacements, but "warning" feels like it's saying "somethings wrong" as opposed to "just so you know".

**Comment by agjohnson** [comment]
[I was thinking more verbose, like a full heading. I put up some changes at https://github.com/readthedocs/readthedocs-client/pull/37 but there are a lot. Noted in chat, but this has some illustration of a web component pattern using Lit. This greatly reduced the CSS and the shadow  dom isolation makes CSS styling easier.

I'll have some notes here as well, I didn't really get around to that yet. The individual commits have some more digestible changes at least.](https://github.com/readthedocs/readthedocs-client/pull/37)

**Comment by agjohnson** [comment]
Should be :+1: to merge this and continue I think!

I forgot to mention, I added a style catalog sort of test suite in the dev server at http://localhost:8000/index.html, you can see a bunch of examples there now.

**Comment by humitos** [comment]
I'm going to merge this and make my changes in different PRs.

**Pull request merged**
